# interface-param.yaml

# Created on: Apr 12, 2025

# Author: Gabriel Toffanetto França da Rocha

# Laboratory of Autonomous Mobility (LMA)
# School of Mechanical Engineering (FEM)
# University of Campinas (Unicamp)

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
  
 vilma_interface:
    ros__parameters:

        # MicroAutoBox UDP communication
        pc_udp_port: 5001
        ma_udp_port: 5001
        udp_timeout_ms: 4
        ma_ip: "192.168.140.3"
        ma_timer_period_ms: 10
        ma_sleep_period_min: 2

        # Controller
        kp_vel: 0.05
        ki_vel: 0.0001
        kd_vel: 0.0
        int_max: 2500.0
        output_min: -0.8
        output_max: 0.3
        
        brake_deadband: -0.1
        speed_reference_ramp_rate: 1.0
        brake_user_pressure_set_emergency: 20.0
        delay_to_user_command_ms: 200
        autonomous_shift_enable: false
        control_timer_period_ms: 100
        
        # Timeout
        joystick_command_time_validity_ms: 500
        communication_timeout_ms: 1000
        autoware_command_time_validity_ms: 250

        # Vehicle
        max_steering_tire_angle_rad: 0.4410 # 25.27 degrees
        max_gas_value: 1.0
        max_brake_value: 1.0
        max_speed_km_h: 60.0

        # Debug
        debug_mode: true
        gas_user_value_set_manual: 0.20